// Generated by scripts/generate-font-packs.mjs. Do not edit by hand.
export const FONT_PACK_MANIFEST = [
    {
        "id": "asana",
        "name": "Asana Math",
        "fontVersion": "4.1.3",
        "fileName": "mathjax-font-asana-4.1.3.json.gz",
        "sha256": "fcd0a84755ab1079ae4a87ed5ccdcd3ff17d04ca898be5365b844d46f60f1a97",
        "compressedBytes": 9397722,
        "uncompressedBytes": 27453949
    },
    {
        "id": "bonum",
        "name": "Gyre Bonum",
        "fontVersion": "4.1.3",
        "fileName": "mathjax-font-bonum-4.1.3.json.gz",
        "sha256": "b404e82c846e5fc8452758405e3a3e58b42a8ddfc4544024b8cef47eaa98f22e",
        "compressedBytes": 8976818,
        "uncompressedBytes": 28107262
    },
    {
        "id": "dejavu",
        "name": "Gyre DejaVu",
        "fontVersion": "4.1.3",
        "fileName": "mathjax-font-dejavu-4.1.3.json.gz",
        "sha256": "ef570484e440f1a3693fa678c00f3625a1b7cc3b5f422d68a59dbaad354e6e26",
        "compressedBytes": 8571391,
        "uncompressedBytes": 26621058
    },
    {
        "id": "fira",
        "name": "Fira Math",
        "fontVersion": "4.1.3",
        "fileName": "mathjax-font-fira-4.1.3.json.gz",
        "sha256": "ab2c251fea7c6122148e832923b57511a4172144b47bf1decd5027ad6ecde21b",
        "compressedBytes": 12105665,
        "uncompressedBytes": 41679663
    },
    {
        "id": "modern",
        "name": "Latin Modern",
        "fontVersion": "4.1.3",
        "fileName": "mathjax-font-modern-4.1.3.json.gz",
        "sha256": "83b4f3dcfa4f51bd33fbd69053e9f76c9626965acb0fca62aa540e55f07a3f3b",
        "compressedBytes": 11703569,
        "uncompressedBytes": 36502303
    },
    {
        "id": "pagella",
        "name": "Gyre Pagella",
        "fontVersion": "4.1.3",
        "fileName": "mathjax-font-pagella-4.1.3.json.gz",
        "sha256": "6199e1cd3b79b9b6b5de683d4ae4b1629d56d07990866de67a3947b1d5898057",
        "compressedBytes": 10478656,
        "uncompressedBytes": 32602661
    },
    {
        "id": "schola",
        "name": "Gyre Schola",
        "fontVersion": "4.1.3",
        "fileName": "mathjax-font-schola-4.1.3.json.gz",
        "sha256": "243e9527eb688fbf70d68e83cdbff416d48f07711dfca89b8c52c6ec5f818269",
        "compressedBytes": 11139550,
        "uncompressedBytes": 33157561
    },
    {
        "id": "stix2",
        "name": "STIX Two",
        "fontVersion": "4.1.3",
        "fileName": "mathjax-font-stix2-4.1.3.json.gz",
        "sha256": "5c434eda9e9492cede9838e695d8f4efdc8a45b49d9802f8baf216356ee62385",
        "compressedBytes": 19301788,
        "uncompressedBytes": 61562937
    },
    {
        "id": "termes",
        "name": "Gyre Termes",
        "fontVersion": "4.1.3",
        "fileName": "mathjax-font-termes-4.1.3.json.gz",
        "sha256": "2253c3be612d1746f62eef794d52e3bb96da4dfe48848ef777f50d8e8af5cdd0",
        "compressedBytes": 9198679,
        "uncompressedBytes": 28507021
    },
    {
        "id": "tex",
        "name": "MathJax TeX",
        "fontVersion": "4.1.3",
        "fileName": "mathjax-font-tex-4.1.3.json.gz",
        "sha256": "4a5ca3a50e783ef47db656661a53c7e87bedd8d56a75352facc0bb64f156563d",
        "compressedBytes": 8189857,
        "uncompressedBytes": 21845245
    }
] as const;
