// Generated by scripts/generate-font-packs.mjs. Do not edit by hand.
export const FONT_PACK_MANIFEST = [
    {
        "id": "stix2",
        "name": "STIX Two",
        "fontVersion": "4.1.3",
        "fileName": "mathjax-font-stix2-4.1.3.json.gz",
        "sha256": "33b5bb4e24b934d95075ddb87a13d16b44a3046efe8de649ed26bc84bb4f011c",
        "compressedBytes": 19301788,
        "uncompressedBytes": 61562937
    },
    {
        "id": "fira",
        "name": "Fira Math",
        "fontVersion": "4.1.3",
        "fileName": "mathjax-font-fira-4.1.3.json.gz",
        "sha256": "89a8988526ed4264232b7ea5167254f06a9306077e4912e0c16fb25ff26fa6f9",
        "compressedBytes": 12105665,
        "uncompressedBytes": 41679663
    }
] as const;
