import { readFileSync, statSync } from "node:fs";

function json(path) {
    return JSON.parse(readFileSync(path, "utf8"));
}

const pkg = json("package.json");
const manifest = json("manifest.json");
const versions = json("versions.json");
const errors = [];

if (pkg.version !== manifest.version) {
    errors.push(`package.json ${pkg.version} != manifest.json ${manifest.version}`);
}
if (process.env.RELEASE_TAG && process.env.RELEASE_TAG !== manifest.version) {
    errors.push(
        `release tag ${process.env.RELEASE_TAG} != manifest version ${manifest.version}`,
    );
}
if (versions[manifest.version] !== manifest.minAppVersion) {
    errors.push(
        `versions.json does not map ${manifest.version} to ${manifest.minAppVersion}`,
    );
}
for (const path of ["main.js", "manifest.json", "styles.css"]) {
    if (statSync(path).size === 0) errors.push(`${path} is empty`);
}
if (!readFileSync("main.js", "utf8").startsWith("/*\nTHIS IS A GENERATED/BUNDLED FILE")) {
    errors.push("main.js is not the expected production bundle");
}

if (errors.length) {
    console.error(errors.map((error) => `- ${error}`).join("\n"));
    process.exit(1);
}
console.log(
    `release metadata valid: Latest MathJax ${manifest.version}, Obsidian >= ${manifest.minAppVersion}`,
);
